services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"   # InfluxDB Port
    environment:
      INFLUXDB_ADMIN_USER: ${INFLUXDB_ADMIN_USER:-admin}
      INFLUXDB_ADMIN_PASSWORD: ${INFLUXDB_ADMIN_PASSWORD:-passw0rd}
      INFLUXDB_BUCKET: ${INFLUXDB_BUCKET:-my_bucket}
      INFLUXDB_ORG: ${INFLUXDB_ORG:-my_org}
    volumes:
      - influxdb_data:/var/lib/influxdb2
    networks:
      - influxdb_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/health"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  influxdb_data:

networks:
  influxdb_net:
