services:
  etcd:
    image: quay.io/coreos/etcd:v3.5
    container_name: etcd
    restart: unless-stopped
    ports:
      - "2379:2379" # Client API
      - "2380:2380" # Peer communication
    environment:
      ETCD_NAME: etcd-single
      ETCD_DATA_DIR: /etcd-data
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_ADVERTISE_CLIENT_URLS: http://localhost:2379
      ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
      ETCD_INITIAL_ADVERTISE_PEER_URLS: http://localhost:2380
      ETCD_INITIAL_CLUSTER: etcd-single=http://localhost:2380
      ETCD_INITIAL_CLUSTER_TOKEN: etcd-cluster-1
      ETCD_INITIAL_CLUSTER_STATE: new
    volumes:
      - etcd_data:/etcd-data
    networks:
      - etcd_net
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  etcd_data:

networks:
  etcd_net:

